### ISSUE TITLE
Allow specifying all required first run configuration values via CLI for easier docker stack templating 

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#1157]
This is how i configured traefik for its first run:

```yaml
version: "3.2"
services:
  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=http"
      - "--certificatesresolvers.myresolver.acme.preferredchain=DST Root CA X3"
      - "--certificatesresolvers.myresolver.acme.email=traefik@tgstation13.org"
      - "--providers.docker"
      - "--providers.docker.swarmmode=true"
      - "--providers.file.directory=/etc/traefik/conf.d/"
      - "--providers.file.watch=true"
...
```

or rather, *this* is how I configured traefik for its first run:

![image](https://user-images.githubusercontent.com/7069733/100854095-65c52380-343d-11eb-8ff9-4ba90145204e.png)
